# Top Level Project Makefile

# The name of the project.
project :=

# The recursive directories that are the components of the project, listed in desired build order.
targets :=

include templates/Makefile.top.mk

# Add any explicit target dependencies here:
